version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: npm run build
    volumes:
      - ./:/app

  aws_deployment:
    image: codeship/aws-deployment
    encrypted_env_file: aws-deployment.env.encrypted
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
    volumes_from:
      - web
