version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm start
